### ISSUE TITLE
Node12系への対応

### ISSUE THREAD

**Issue by kadora626** [qramana/qramana#53]
Node.jsの最新は12系なのでそれにも対応しておきたい。
また、Node.jsはすでにLTSが10系になってるので8系をtravisの設定から削除しても良いかも。

**Comment by kadora626** [comment]
ローカルで12系のNode使ってたからtravisの設定から12 in 8 outで十分かも

**Comment by kamakiri01** [comment]
travisの対象バージョンを12にしたPR出してみて、CI通れば上げてよいと思います。
